/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dark_
 */
public class fmMenu extends javax.swing.JFrame {

    /**
     * Creates new form fmMenu
     */
    public fmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btIngresso = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        laData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mCadastroFuncionario = new javax.swing.JMenuItem();
        mHistoricoVendas = new javax.swing.JMenuItem();
        mGerenciarFilmes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Cinema");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(41, 73, 116));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btIngresso.setBackground(new java.awt.Color(255, 255, 255));
        btIngresso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btIngresso.setText("Ingresso");
        btIngresso.setFocusable(false);
        btIngresso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btIngresso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngressoActionPerformed(evt);
            }
        });
        jToolBar1.add(btIngresso);

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btSair);

        jPanel1.setBackground(new java.awt.Color(53, 94, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        laData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laData.setForeground(new java.awt.Color(255, 255, 255));
        laData.setText("Data:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bem-Vindo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laData)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laData)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Atendente");

        jMenuItem1.setText("Ingresso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gerente");

        mCadastroFuncionario.setText("Cadastro funcionario");
        mCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(mCadastroFuncionario);

        mHistoricoVendas.setText("Histórico de vendas");
        mHistoricoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHistoricoVendasActionPerformed(evt);
            }
        });
        jMenu2.add(mHistoricoVendas);

        mGerenciarFilmes.setText("Gerenciar filmes");
        mGerenciarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGerenciarFilmesActionPerformed(evt);
            }
        });
        jMenu2.add(mGerenciarFilmes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (hierarquia==false){
            mCadastroFuncionario.setEnabled(false);
            mHistoricoVendas.setEnabled(false);
            mGerenciarFilmes.setEnabled(false);
        }
        
        final Runnable threadRelogio = new Runnable() {
            public void run() {
                try{
                    int x=0;
                    while(x==0){  
                        DateFormat dateformat = new SimpleDateFormat ("dd/MM/yyyy HH:mm:ss");
                        Date date = new Date();
                        laData.setText(dateformat.format(date));
                        Thread.sleep(1000);
                    }
                } catch (Exception e){}
            }
        };    
        new Thread(threadRelogio).start();
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        System.out.println(idFunc);
    }//GEN-LAST:event_formWindowOpened

    private void mGerenciarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGerenciarFilmesActionPerformed
        fmGerenciarFilmes filmes = new fmGerenciarFilmes();
        jDesktopPane1.add(filmes);
        filmes.setVisible(true);
    }//GEN-LAST:event_mGerenciarFilmesActionPerformed

    private void mCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroFuncionarioActionPerformed
        fmFuncionario funcionario = new fmFuncionario();
        jDesktopPane1.add(funcionario);
        funcionario.setVisible(true); 
    }//GEN-LAST:event_mCadastroFuncionarioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        fmSobre sobre = new fmSobre();
        jDesktopPane1.add(sobre);
        sobre.setVisible(true); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mHistoricoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHistoricoVendasActionPerformed
        fmHistoricoVendas vendas = new fmHistoricoVendas();
        jDesktopPane1.add(vendas);
        vendas.setVisible(true);
    }//GEN-LAST:event_mHistoricoVendasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        fmBilhete ingresso = new fmBilhete();
        jDesktopPane1.add(ingresso);
        ingresso.setIdFunc(idFunc);
        ingresso.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        int valor = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Sistema de Prontuários Médicos",1);
        if(valor==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void btIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngressoActionPerformed
        fmBilhete ingresso = new fmBilhete();
        jDesktopPane1.add(ingresso);
        ingresso.setVisible(true);
        ingresso.setIdFunc(idFunc);
    }//GEN-LAST:event_btIngressoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmMenu().setVisible(true);
            }
        });
    }
    private Boolean hierarquia;
    private int idFunc;
    public Boolean setHierarquia(Boolean hierarquia){
        return this.hierarquia=hierarquia;
    }
    public int setIdFunc(int idFunc){
        return this.idFunc=idFunc;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngresso;
    private javax.swing.JButton btSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel laData;
    private javax.swing.JMenuItem mCadastroFuncionario;
    private javax.swing.JMenuItem mGerenciarFilmes;
    private javax.swing.JMenuItem mHistoricoVendas;
    // End of variables declaration//GEN-END:variables
}
